### ISSUE TITLE
Accelerate checking of current targets

### ISSUE THREAD

**Issue by krlmlr** [wlandau/parallelRemake#4]
The goal would be to recreate a file tree for all data targets before the actual processing of the rules. This could work like this:

- All data targets are renamed to `.data/<name>` instead of `<name>`
- All targets depend on a phony target `.init`, which does the following:
    - Create the `.data` directory
    - Determine up-to-dateness with *one* call to `remake::is_current()`
    - For each target, create the corresponding file with the correct timestamp:
        - clean targets: now
        - dirty targets: yesterday
- Then `make` would always run `.init` first, and from there on only dirty targets need to be touched at all.

If this works it would be a better alternative to #3. I wanted to check back with you if you considered something like this.

**Comment by wlandau** [comment]
Creating files just for the timestamps did cross my mind, but I wasn't sure how to implement it cleanly. Mainly, I didn't think there was a platform-independent way to manually set the timestamp of a file. If there is, then your idea seems to do the job.

**Comment by krlmlr** [comment]
Good point. If I'm not mistaken, all we need is two empty files with different timestamps. We could ship a .zip file with two such files and extract it to /tmp.

**Comment by wlandau** [comment]
Clever! We could ship the zip in `inst` and copy it over with `system.file(..., package = "parallelRemake")`. But should we use `/tmp`? Windows may use a different temp folder, and `/tmp` on Mac/Linux could empty in the middle of a days-long batch of jobs. Also, how would we copy those two files to the individual `.data/<name>` files while preserving the timestamps? It could be a pain to extract the zip again for every target.

I guess an alternative `.init` might:
1. Use an initialization Makefile to create all the `.data/<name>` files in the correct order.
2. Wait a few milliseconds.
3. Recreate the dirty targets' `.data/<name>` files in any order.

**Comment by wlandau** [comment]
Also, I keep thinking that it would be really cool to somehow use the information already in the `.remake` storr cache, though I doubt it's possible for this purpose.

**Comment by krlmlr** [comment]
Relevant: http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time

We need to extract the mini-zip only once, during computation of `.init`. `file.copy(copy.data = TRUE)` takes care of copying the timestamp.

I have considered waiting, but currently I'm still in favor of the .zip file approach.

**Comment by krlmlr** [comment]
@jeroenooms @s-u: Are you aware of a portable way to assign a modification time to a file in R? This is for creating an environment for `make` so that some (otherwise phony) targets are "clean" and others are "dirty".

**Comment by wlandau** [comment]
Hmm... what if all the targets are dirty? Wouldn't Make see everything as up to date since all the timestamps are the same? What if we do the following instead?

1. During `.init`, empty out the `.data` directory and create dummy files for all the clean targets, all with the same modification time. (All copied from a zipped, shipped file with an ancient timestamp.)
2. Add a line at the end of every recipe to create `.data/<name>`.

**Comment by wlandau** [comment]
@krlmlr, I had a crack at this issue in the `timestamp-files` branch. I did it according to my previous comment, with a single file in `timestamp.zip` copied over for every clean target with the timestamp preserved. Dirty targets were not given timestamp files. I ran into a couple of snags, which I also explained in the commit messages.

First setback: I found out the hard way that if a non-phony target depends on a phony target, then it can't be skipped, at least with Make v3.81 on Mac OS 10.12.2. So having a phony `.init` target defeats the purpose of #4 entirely. Solution:

```r
INIT := $(shell Rscript -e 'parallelRemake:::init_timestamps("remake.yml")')
```

That way, we have a guaranteed prebuild step that doesn't use phony targets. 

Second setback: either I'm missing something or `remake::is_current()` only checks adjacent nodes on the dependency tree. Solution: create a new timestamp file with a new timestamp for every target that is made in the current session. The zipped timestamp file is guaranteed to have a much earlier timestamp, which appeared to make the correct build decisions happen.

**Comment by wlandau** [comment]
And yet...there still may be a slick way to ignore everything up to the first dirty target. That would be useful. I'm not sure how to do it, though. It would probably require more digging into remake itself.

**Comment by wlandau** [comment]
Just fixed the issue and updated my long comment.

**Comment by krlmlr** [comment]
Thanks for looking into it. I'll report when I have applied this in practice.

**Comment by krlmlr** [comment]
Can we define a non-phony target `.data/..remakeTargets` that depends on a phony target but itself is a proper target?

**Comment by wlandau** [comment]
Sure. What does `.data/..remakeTargets` do?

**Comment by wlandau** [comment]
I just realized: `.init` should really be an empty target, not a preprocessing step. That way, `make clean` is unaffected. `make .init` should copy the date from `inst/timestamp.zip` to `.data/.init`, and `.init` should be an illegal target name.

**Comment by krlmlr** [comment]
This is a regular file that is created/updated once we have populated our temporary directory.

**Comment by wlandau** [comment]
Oh, you mean as a replacement for `$(shell ...)`. That would let us to bypass `init_timestamps()` for `make("clean")`. Much better. Yes, let's do that.

**Comment by wlandau** [comment]
It just occurred to me: if we wrote the timestamp files in topological order, we wouldn't need to use the zip file except for `.data/..remakeTargets`. We could borrow from [remake/R/graph.R](https://github.com/richfitz/remake/blob/master/R/graph.R), but `igraph::topological.sort()` may be cleaner and easier.

**Comment by wlandau** [comment]
Hmmm... I'm actually having second thoughts about `.data/..remakeTargets`. I'm playing around with a version of this, and sometimes when I make a change to my project code, I need two calls to Make to get the right targets to update. Either I'm implementing it wrong, or maybe Make gets all the initial timestamp information at once just before any targets are made. Also, it seems like using `.data/..remakeTargets` in the way I pictured could involve resetting the same`.data/<name>` using two different targets. If that were enough to confuse Make, I wouldn't be surprised. Plus, `$(shell` (or the more portable backticks) + `igraph::topological.sort()`, allows us to drop the zip file, and we'd even get a nice `make: Nothing to be done for `all'.` message at the right times.

If you know how to make work, though, it may still be worth the performance gains for `make("clean")`.

**Comment by wlandau** [comment]
FYI: [I'm having some trouble with portable Makefiles](http://stackoverflow.com/questions/42219071/portable-makefiles-that-call-rscript). Backticks are more portable than `$(shell`, but I haven't gotten them to work.

**Comment by wlandau** [comment]
According to the [Make docs](https://www.gnu.org/software/make/manual/html_node/Secondary-Expansion.html#Secondary-Expansion), there's separate "read-in" phase before the "target-update" phase, which I think is what's interfering with the use of `.data/..remakeTargets`. We might try `.SECONDEXPANSION`, but I'm not sure if that's portable.

**Comment by wlandau** [comment]
FYI: I think the second `Makefile` in [this question](http://stackoverflow.com/questions/42219071/portable-makefiles-that-call-rscript?noredirect=1#comment71628786_42219071) (the edit) has a solution we could use: backticks instead of `$(shell ...)` for portability and the option to skip `make clean`. 

**EDIT**: on second thought, that doesn't totally solve it. The up-to-date timestamps prevent evaluating the things in backticks. So close yet so far, for the third or fourth time in a row.

**Comment by wlandau** [comment]
Okay, I think I finally cracked it. What if we have a single function to both create and call the `Makefile` from inside R? We could make the timestamps beforehand without worrying about strange behavior from Make. I'm picturing something like 

```r
run_makefile = function(..., sources = ..., run = TRUE, command = "make -j 2"){
    ...
    write_timestamps(...) # topological order. No need for a zip file or hackish phony target
    if(run) system(command)
}
```

I don't know when I'll be able to get around to implementing this, but I'm optimistic that this could be the right thing to do.

**Comment by krlmlr** [comment]
It's difficult to get `make` to do the right thing...

Consider this example:

```Makefile
all: a b c

a: b c
	touch $@

b:
	touch $@; touch c

c:
	touch $@
```

Both `make -n` and `make -j 2` execute the rule for `c`, but not `make -j 1`. It may be that parallel `make` behaves differently w.r.t. rules that create undocumented prerequisites as a side effect. Indeed, the problem may be harder than anticipated.

With your last suggestion: What happens if the user just types `make` on the terminal? I'm not sure we should include `-j 2` in the default command line.

**Comment by wlandau** [comment]
I'm fine with dropping `-j 2`.

The way I'm seeing it, the user shouldn't type `make` in the terminal. But I don't think that's such a loss. We still have all the functionality we want, even with the extra R wrapper. Plus, we wouldn't need any phony targets in except for "all". That really shortens and cleans up the Makefile. We wouldn't even need to define a "clean" target since the user is in R anyway and can call `remake::make("clean")`.

```r
all: .data/a .data/b .data/c

.data/a: .data/b .data/c
	parallelRemake::build("a") # remake::make("a") plus whatever else we need.

.data/b:
	parallelRemake::build("b")

.data/c:
	parallelRemake::build("c")
```

**Comment by wlandau** [comment]
Now using R to write the timestamps. Makefiles are no longer standalone, but that's okay. Just put `makefile()` in an R script that you call from the command line.

**Comment by krlmlr** [comment]
@wlandau: Is there any reason why we can't have a static `Makefile`? I feel safer if I put it under version control.

**Comment by wlandau** [comment]
The only reason is that I haven't figured out how to make a static `Makefile` work. All the little hacks I tried before require tricking Make and have unavoidable snags. With version control in mind, I did recently remove the "generated by parallelRemake..." line at the top. Is there something else I'm missing here?

**Comment by krlmlr** [comment]
I mean that `makefile()` currently both creates the `Makefile` and runs it. Do we really need to always recreate the `Makefile`? If not, we could perhaps keep `write_makefile()` and just define a `run()` function.

**Comment by wlandau** [comment]
My only concern is that the user may change `remake.yml` or `workflow.R` and then forget to update the `Makefile`. But mostly, I think it's a matter of style. In any case, it's a good point.

**Comment by krlmlr** [comment]
I've had some success with a standalone `Makefile`. This is `Makefile.parallel`:

```Makefile
all:
Makefile.dummy:
        Rscript -e 'parallelRemake::makefile(prepend = "include Makefile.parallel", run = FALSE)'
-include Makefile.dummy
```

In `Makefile`, I just add `include Makefile.parallel` to include it. The `-include` triggers an unconditional build of `Makefile.dummy`, which is never created. It looks like `make` picks up the updated timestamps.

I tested this with GNU Make, lsmake currently doesn't work for me. I'm not sure how standard the `-include` is, though.

**Comment by wlandau** [comment]
Thanks for the option. I'm glad to know this can be done on at least one flavor of Make.

**Comment by krlmlr** [comment]
What flavor did you test with?

**Comment by wlandau** [comment]
I was just commenting on the fact that it worked on the GNU variety of Make for you. I haven't yet tested it myself.

**Comment by krlmlr** [comment]
Yeah, the [Open Group specs](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html) don't seem to mention `-include`. What other flavors of Make do you want `parallelRemake` to be compatible with?

**Comment by krlmlr** [comment]
Even simpler:

```
all:
.PHONY:
Makefile.parallel: .PHONY
	Rscript -e 'parallelRemake::makefile(prepend = "include Makefile.parallel", run = FALSE)'
```

I guess we could include this logic in the `Makefile` we create by default (with `Makefile` as target). Worst thing that can happen is that this rule isn't executed, we instruct the user to fall back to `makefile()` if `make -n` remains silent.

**Comment by wlandau** [comment]
I was going to say that the [R Extensions manual section 1.6](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-portable-packages) say to use those Open Group specs you mentioned, and your latest comment would seem to fit the guidelines.

**Comment by krlmlr** [comment]
I'm currently working on the code that writes Makefiles (on top of #11), I'll submit a PR in due time.

**Comment by wlandau** [comment]
By the way: for timestamps, I'd like to take back what I said about writing timestamp files in topological order. Your idea of shipping a zip file with an old timestamp is much better. The precision of timestamps can vary from system to system, so creating new timestamps and then immediately using them could cause some targets to be incorrectly skipped.
