### ISSUE TITLE
Mention lsmake in documentation

### ISSUE THREAD

**Issue by krlmlr** [wlandau/parallelRemake#5]
A drop-in replacement for `make` that runs jobs on workers in an LSF cluster. We should make sure to create compatible Makefiles.

**Comment by wlandau** [comment]
I had not heard of lsmake until now. Do you think accommodating LSF is as simple as prepending the appropriate lines to a Makefile?

**Comment by krlmlr** [comment]
It's simpler, just run `lsmake` instead of `make`. But it probably doesn't support all of the latest features of GNU Make.
